# ┌─────────────────────────────────────────────────────────────────────────┐
# │             FICHIER: /_config.yml                                       │
# └─────────────────────────────────────────────────────────────────────────┘

# 1. Informations générales
title: "Cyprien – Programmatic SEO"  
lang: fr-FR  
markdown: kramdown

# 2. URL + BaseURL (indispensable pour que Jekyll génère des liens corrects)
url: "https://cypskippy.github.io"    # ta racine publique (sans slash final)
baseurl: "/Tips"                      # le sous-répertoire GitHub Pages

# 3. Plugins pour sitemap et balises SEO
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# 4. Permalink global par défaut (utilisé si un fichier n'a pas de front matter spécifique)
permalink: /:title/

# 5. Définition de la "collection" pages
collections:
  pages:
    output: true
    permalink: /:name/    # /nom-du-fichier-sans-.md/

# 6. Front matter DEFAULTS : toutes les pages de type "pages" auront layout: page
defaults:
  - scope:
      path: ""            # toutes racines confondues
      type: pages         # dépêche-toi de créer un dossier _pages !
    values:
      layout: page

# 7. (Optionnel) Configuration additionnelle pour SEO
#    Par exemple, si tu veux un logo, des meta “twitter”, etc. Tu peux garder ce bloc pour plus tard.
 

