# ┌─────────────────────────────────────────────────────────────────────────┐
# │  FICHIER : _config.yml – configuration Jekyll                          │
# └─────────────────────────────────────────────────────────────────────────┘

# 1. Informations générales
title: "Cyprien – Programmatic SEO"
lang: fr-FR
markdown: kramdown

# 2. URL de production (sans slash final) et baseurl (sous-répertoire GitHub Pages)
url: "https://cypskippy.github.io"
baseurl: "/tips"               # si tu publies dans la racine, mets ""

# 3. Plugins officiels activés
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# 4. Permalien par défaut pour les pages/collections sans front-matter spécifique
permalink: /:title/

# 5. Déclaration de la collection “tips” (les fichiers dans _tips/)
collections:
  tips:
    output: true
    permalink: /tips/:path/

# 6. Valeurs par défaut appliquées aux documents de la collection
defaults:
  - scope:
      path: ""
      type: tips
    values:
      layout: page
