# ┌─────────────────────────────────────────────────────────────────────────┐
# │             FICHIER: /_config.yml                                       │
# └─────────────────────────────────────────────────────────────────────────┘

# 1. Informations générales
title: "Cyprien – Programmatic SEO"  
lang: fr-FR  
markdown: kramdown

# 2. URL + BaseURL (indispensable pour que Jekyll génère des liens corrects)
url: "https://cypskippy.github.io"    # ta racine publique (sans slash final)
baseurl: "/tips"                      # le sous-répertoire GitHub Pages

# 3. Plugins pour sitemap et balises SEO
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


# 4. Permalink global par défaut (utilisé si un fichier n'a pas de front matter spécifique)
permalink: /:title/

# 5. Définition de la "collection" pages
collections:
  tips:
    output: true
    permalink: /tips/:path/
defaults:
  - scope:
      path: ""
      type: tips
    values:
      layout: page
    
yml\ncollections:\n tips:\n output: true\n permalink: /tips/:path/\n




# 7. (Optionnel) Configuration additionnelle pour SEO
#    Par exemple, si tu veux un logo, des meta “twitter”, etc. Tu peux garder ce bloc pour plus tard.
 

