# ┌─────────────────────────────────────────────────────────────────────────┐
# │            FICHIER: .github/workflows/generate.yml                     │
# └─────────────────────────────────────────────────────────────────────────┘

name: Génération et Déploiement Automatique

# On doit autoriser le token à écrire dans le dépôt
permissions:
  contents: write

on:
  schedule:
    - cron: "0 3 * * *"     # se déclenche chaque nuit à 03h00 CET (02h00 UTC)
  workflow_dispatch:       # permet de lancer manuellement depuis l’interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. On récupère le code du repo
      - name: Checkout du repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2. On installe Python (pour exécuter generate.py)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. On installe les dépendances du script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. On exécute le script qui génère les .md dans _pages/
      - name: Generate content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate.py

      # 5. On commit et push les nouveaux fichiers si nécessaire
      - name: Commit & push new articles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "bot@github"
          git config --global user.name "Content-Bot"
          git add _tips/ || true
          # On ne commit QUE s'il y a un changement dans _pages/
          git diff --quiet && echo "Aucun changement dans _pages/" || \
            git commit -m "chore(content): auto-update $(date -u +%F)"
          git push origin HEAD:main

      # 6. On ping Google pour indiquer que le sitemap a changé
      - name: Ping Google pour le sitemap
        run: |
          curl -I "https://cypskippy.github.io/Tips/sitemap.xml" \
            --silent --output /dev/null --head
